/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 81ea2043e1b6131333b775277475b9a9)
interface __BaseEnv_Env {
	IMAGE_ASSETS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	CF_ACCESS_TEAM_DOMAIN: "https://jolly-glitter-da93.cloudflareaccess.com";
	CF_ACCESS_AUD: "d7990901bf79388de024fee36a5a8abcd4452ff4c908acfa19189b37856fb30b";
	EDITORIAL_ALLOWED_EMAIL: "klsmallwood73@gmail.com";
	MODEL_PROVIDER: "openai";
	MODEL_NAME: "gpt-5.6-terra";
	MODEL_GENERATION_ENABLED: "true";
	MODEL_DAILY_BUDGET_MICRO_USD: "1000000";
	IMAGE_PROVIDER: "replicate";
	IMAGE_MODEL: "black-forest-labs/flux-2-pro";
	IMAGE_GENERATION_ENABLED: "false";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "EDITORIAL_ALLOWED_EMAIL" | "MODEL_PROVIDER" | "MODEL_NAME" | "MODEL_GENERATION_ENABLED" | "MODEL_DAILY_BUDGET_MICRO_USD" | "IMAGE_PROVIDER" | "IMAGE_MODEL" | "IMAGE_GENERATION_ENABLED">> {}
}
