/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 68fdd5a9b98a1c89b5e97a3b46f37a68)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	CF_ACCESS_TEAM_DOMAIN: "https://jolly-glitter-da93.cloudflareaccess.com";
	CF_ACCESS_AUD: "d7990901bf79388de024fee36a5a8abcd4452ff4c908acfa19189b37856fb30b";
	EDITORIAL_ALLOWED_EMAIL: "klsmallwood73@gmail.com";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "EDITORIAL_ALLOWED_EMAIL">> {}
}
