/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c7aa480b7c7e4884fb15e02999675b67)
interface __BaseEnv_Env {
	IMAGE_ASSETS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	CF_ACCESS_TEAM_DOMAIN: "https://jolly-glitter-da93.cloudflareaccess.com";
	CF_ACCESS_AUD: "d7990901bf79388de024fee36a5a8abcd4452ff4c908acfa19189b37856fb30b";
	EDITORIAL_ALLOWED_EMAIL: "klsmallwood73@gmail.com";
	MODEL_PROVIDER: "openai";
	MODEL_NAME: "gpt-5.6-terra";
	MODEL_GENERATION_ENABLED: "true";
	MODEL_DAILY_BUDGET_MICRO_USD: "1000000";
	IMAGE_PROVIDER: "cloudflare-ai-gateway";
	IMAGE_MODEL: "openai/gpt-image-2";
	IMAGE_GENERATION_ENABLED: "true";
	CLOUDFLARE_ACCOUNT_ID: "13fbf38daabf893cddf8e7214957bfce";
	CLOUDFLARE_AI_GATEWAY_ID: "tomorrow-ish";
	IMAGE_WEBHOOK_ORIGIN: "https://tomorrow-ish.news";
	ADS_ENABLED: "false";
	ADSENSE_ARTICLE_INLINE_1_SLOT: "";
	ADSENSE_ARTICLE_INLINE_2_SLOT: "";
	ADSENSE_DESKTOP_SIDEBAR_SLOT: "";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "EDITORIAL_ALLOWED_EMAIL" | "MODEL_PROVIDER" | "MODEL_NAME" | "MODEL_GENERATION_ENABLED" | "MODEL_DAILY_BUDGET_MICRO_USD" | "IMAGE_PROVIDER" | "IMAGE_MODEL" | "IMAGE_GENERATION_ENABLED" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_AI_GATEWAY_ID" | "IMAGE_WEBHOOK_ORIGIN" | "ADS_ENABLED" | "ADSENSE_ARTICLE_INLINE_1_SLOT" | "ADSENSE_ARTICLE_INLINE_2_SLOT" | "ADSENSE_DESKTOP_SIDEBAR_SLOT">> {}
}
